FROM python:3.10-slim-bullseye
WORKDIR /car_protection

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

#install system dependencies
RUN apt-get update

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /car_protection/
RUN pip install -r requirements.txt

COPY ./car_protection

ENTRYPOINT ["gunicorn","core.wsgi"]
